modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "spider_webber"
version = "1.0.0"
displayName = "Spider Webber"
displayURL = ""
logoFile = ""
credits = "Impulse"
authors = "Impulse"
description = '''
Spiders place webs
'''

[[dependencies.spider_webber]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spider_webber]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spider_webber]]
modId = "midnightlib"
mandatory = true
versionRange = "[1.9.2,)"
ordering = "AFTER"
side = "BOTH"